### ISSUE TITLE
Translate "How to modify headers" to English 

### ISSUE THREAD

**Issue by zhaohuabing** [aeraki-mesh/website#8]

**Comment by wuseyu** [comment]
我不太确定这个pr是不是需要翻译这个文件...
![image](https://user-images.githubusercontent.com/96163054/167286050-67ec6b9c-2b10-43d3-8d42-fb1a7622a10b.png)
还是其他的文件呢

**Comment by zhaohuabing** [comment]
是这个

**Comment by wuseyu** [comment]
好的
